### PR TITLE
some regex of the email and css for the button sent

### PR DESCRIPTION
**Pull request by Hacene010**

### CODE REVIEW

**Review by GeorgesFORTRY — DISMISSED** [review]
ok

**Review by GeorgesFORTRY — DISMISSED** [review]
ok

**Review by GeorgesFORTRY — DISMISSED** [review]
ok

**Review by GeorgesFORTRY — APPROVED** [review]
ok

**Comment by LoicBrassart** [comment]
@Hacene010 Love the commit messages, they're super clean :ok_hand:

**Review by LoicBrassart — APPROVED** [review]
SnE

**Comment by Hacene010** [comment]
> @Hacene010 Love the commit messages, they're super clean

Thanks ^ ^

**Pull request merged**
